name: xdncov
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "5 0 * * *"

jobs:
  xdncov:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"
      - name: setup dependencies
        run: python -m pip install -U pip requests
      - name: submit
        env:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          province: ${{ secrets.PROVINCE }}
          city: ${{ secrets.CITY }}
          district: ${{ secrets.DISTRICT }}
          key: ${{ secrets.KEY }}
        run: python xdncov.py
